### PR TITLE
Dennis Nehrenheim - UI Design Patterns Challenge

### PR DESCRIPTION
**Pull request by GrowthPilgrim**

### CODE REVIEW

**Comment by mapostolakis** [comment]
Hi @GrowthPilgrim, if your PR is ready for review, please rename it accordingly, following the instructions in the README file. Thank you 🙂

**Comment by danillahtin** [comment]
Hi @GrowthPilgrim,

This is Danil, I am an instructor at Essential Developer.

The CI build failed.

Please, fix all build failures and let me know once you're done so I can start the review. Thank you 🙂

**Comment by danillahtin** [comment]
Hi @GrowthPilgrim. Do you need any help fixing the tests? Just let me know - We're here to help! 🙂

**Comment by GrowthPilgrim** [comment]
> Hi @GrowthPilgrim. Do you need any help fixing the tests? Just let me know - We're here to help! 🙂

The failing snapshot test seems to be due a very minor UI difference in the `MVC` project which I can't detect visually. The color code is the same as in MVP and MVVM... For some reason, the Xcode project always hangs itself up if I try to run the test locally. So right now it's hard to debug. Maybe it's because I branched off the (now) legacy 12_4 branch? What do you suggest? Should I create a new branch and MR and cherry-pick my commits?

**Comment by danillahtin** [comment]
Hi @GrowthPilgrim,

Yes, branching from xcode12_4 can be an issue.
I couldn't find the branch you are working on in your fork, so I am unable to take a look atm.
It can happen (a bug or a feature I have no idea) that a story board ends up having the same hex code but a different rgb values for colors. 
You can take a look [here](https://github.com/essentialdevelopercom/ios-lead-essentials-ui-design-patterns-challenge/pull/105#pullrequestreview-713805854), it's the same issue I am talking about.
I see that in `MVC Module/Source/Feed UI/Views/Feed.storyboard ` there is a change in color which potentially can be the cause. 
So you can try to fix it on your own or push the actual branch so that I can have a look by myself.

**Comment by danillahtin** [comment]
Hi @GrowthPilgrim. Do you need any help fixing the tests? Just let me know - We're here to help! 🙂

**Comment by danillahtin** [comment]
Hi @GrowthPilgrim,

We’re closing the PR because of inactivity. You can reopen it at any time and finish the challenge. Let us know if you need any help. Thanks!

**Pull request closed without merging**
